### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by codetestmg** [raheemadamboev/image-radio-button-android#3]
Hi 
How to increase image size ?

Thanks

**Comment by raheemadamboev** [comment]
@codetestmg Currently, it's not possible to increase the size of the image of GravityImageRadioButton. You can easily create your own custom RadioButton and increase the size of the image as you want. You can get the idea how to do it by looking at GravityImageRadioButton class. You can use GravityRadioGroup to hold your custom radio buttons.
